#!/usr/bin/env python3
"""Run a Drone fleet Composition: many Drone Core drones in one World.

tools/urban_simulation.py writes the fleet recipe from a Composition `fleets`
entry (docs/asset-contract.md 5.8). configure materializes the Business Pack
drone-fleet-single-host workspace for the fleet, then builds the shared
MuJoCo World with every drone laid out around the launch area
(tools/drone_fleet_city.py). start runs it through the Business Pack
Launcher with the Urban real-time pacer.

The fleet control is Drone Core's RPC show runner (synchronized takeoff, then
the HAKONIWA formation), generated by the Business Pack Launcher writer.

  python tools/drone_fleet.py configure --recipe <fleet-recipe.json>
  python tools/drone_fleet.py doctor|start|status|stop
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT.parent
BUSINESS_PACK_ROOT = WORKSPACE / "hakoniwa-business-pack"
DEFAULT_DRONE_ROOT = WORKSPACE / "hakoniwa-drone-core"
DEFAULT_VIEWER_ROOT = WORKSPACE / "hakoniwa-threejs-drone"
RECIPE_ID = "urban-drone-fleet"
RECIPE_FILE = "urban-fleet-recipe.json"
EXPERIMENT_FILE = "urban-fleet-experiment.yaml"
RECIPE_KEYS = {
    "version", "id", "fleet", "city_receipt", "drone_count", "process_count",
    "spacing_m", "area", "ground_clearance_m", "control",
}
# The Business Pack scenario the show runner flies (letters sampled to the
# drone count; 52 or more drones show the whole word).
SCENARIO = {
    "type": "hakoniwa-word",
    "word": "HAKONIWA",
    "letter_width_m": 2.0,
    "letter_height_m": 4.0,
    "letter_gap_m": 0.9,
    "altitude_m": 5.0,
    "duration_sec": 6.0,
    "hold_sec": 0.0,
    "speed_m_s": 1.0,
    "timeout_sec": 180.0,
    "land": False,
}

for path in (ROOT / "tools", BUSINESS_PACK_ROOT / "tools" / "recipe", BUSINESS_PACK_ROOT / "tools"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import drone_fleet_single_host as base  # noqa: E402
import drone_fleet_city as city  # noqa: E402
import urban_controls  # noqa: E402
import urban_lifecycle  # noqa: E402


class FleetError(RuntimeError):
    pass


def workspace_paths():
    return base.load_foundation_module().resolve_workspace(BUSINESS_PACK_ROOT, RECIPE_ID)


def load_recipe(path: Path) -> dict:
    try:
        recipe = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise FleetError(f"invalid fleet recipe {path}: {exc}") from exc
    if not isinstance(recipe, dict) or set(recipe) != RECIPE_KEYS or recipe.get("version") != 1:
        raise FleetError(f"fleet recipe {path} must be version 1 with {sorted(RECIPE_KEYS)}")
    if not Path(recipe["city_receipt"]).is_file():
        raise FleetError(f"City World receipt not found: {recipe['city_receipt']}")
    return recipe


def configured_recipe(paths) -> dict:
    path = paths.recipe_config / RECIPE_FILE
    if not path.is_file():
        raise FleetError("the fleet is not configured; run configure first")
    return load_recipe(path)


def experiment_path(paths) -> Path:
    return paths.recipe_config / EXPERIMENT_FILE


def write_experiment(paths, recipe: dict) -> Path:
    path = experiment_path(paths)
    path.parent.mkdir(parents=True, exist_ok=True)
    base.write_simple_yaml(path, {
        "version": 1,
        "experiment": {"id": RECIPE_ID},
        "scale": {
            "drone_count": recipe["drone_count"],
            "drones_per_process": "auto",
            "process_count": recipe["process_count"],
        },
        # The Urban pacer paces the whole simulation; the runner does not sleep itself.
        "runtime": {"mode": "native", "visualization": True, "show_runner_real_time_sync": False},
        "scenario": dict(SCENARIO),
        "results": {"enabled": False, "directory": "results"},
    })
    return path


def launch_area(recipe: dict) -> dict:
    """The fleet grid centre in the City World MJCF frame (X north, Y west)."""
    area = recipe["area"]
    return {"mode": "manual", "offset_m": [float(area["north_m"]), -float(area["east_m"]), 0.0]}


def configure(drone_root: Path, recipe_path: Path) -> int:
    recipe = load_recipe(recipe_path)
    paths = workspace_paths()
    (paths.recipe_config / urban_controls.CONTROLS_FILE).unlink(missing_ok=True)
    experiment = write_experiment(paths, recipe)
    rc = base.configure(experiment, drone_root, workspace=paths, write_guide=False)
    if rc != 0:
        return rc
    marker = city.configure_single_host_fleet(
        drone_root=drone_root,
        city_world_path=Path(recipe["city_receipt"]),
        drone_count=recipe["drone_count"],
        process_count=recipe["process_count"],
        recipe_config=paths.recipe_config,
        spawn_altitude_m=recipe["ground_clearance_m"],
        spawn_spacing_m=recipe["spacing_m"],
        altitude_mode="route-clearance",
        launch_area=launch_area(recipe),
    )
    (paths.recipe_config / RECIPE_FILE).write_text(json.dumps(recipe, indent=2) + "\n", encoding="utf-8")
    plan = marker["flight_plan"]
    print("Urban Drone fleet configured")
    print(f"Fleet      : {recipe['fleet']} ({recipe['drone_count']} drones, {recipe['process_count']} process(es))")
    print(f"City World : {recipe['city_receipt']}")
    print(f"Area       : east={recipe['area']['east_m']:.2f} m, north={recipe['area']['north_m']:.2f} m, "
          f"spacing={recipe['spacing_m']:.2f} m")
    print(f"Launch pts : {len(plan['spawn_points'])}")
    print(f"Flight Z   : {plan['resolved_flight_altitude_m']:.3f} m")
    print(f"Fleet file : {marker['fleet_config']}")
    return 0


def launcher_writer():
    """Business Pack Launcher plus the Composition's pacer (urban_controls file)."""

    def write(paths, drone_root, viewer_root, experiment, system_name):
        path = base.write_launcher(paths, drone_root, viewer_root, experiment, system_name)
        return urban_controls.apply_controls_file(path, paths.recipe_config)

    return write


def lifecycle_spec(paths, drone_count: int) -> urban_lifecycle.LifecycleSpec:
    return urban_lifecycle.LifecycleSpec(
        recipe_id=RECIPE_ID,
        recipe_root=paths.recipe_root,
        launcher=paths.recipe_config / "launcher.json",
        session=paths.recipe_root / "runtime/launcher-session.json",
        viewer_url=viewer_url(drone_count),
    )


def viewer_url(drone_count: int) -> str:
    return base.viewer_url(drone_count, map_viewer=True) + "&layout=three-main"


def start(drone_root: Path, viewer_root: Path, recipe_path: Path | None) -> int:
    paths = workspace_paths()
    configured = configured_recipe(paths)
    if recipe_path is not None and load_recipe(recipe_path) != configured:
        # The layout and heights are built at configure (tools/drone_fleet_city.py).
        raise FleetError("the fleet changed since configure (count, area, or spacing); run configure first")
    urban_lifecycle.preflight_start(lifecycle_spec(paths, configured["drone_count"]))
    return base.start(experiment_path(paths), drone_root, viewer_root, workspace=paths,
                      launcher_writer=launcher_writer())


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    result.add_argument("command", choices=("configure", "doctor", "start", "status", "stop", "viewer-url"))
    result.add_argument("--recipe", type=Path, help="fleet recipe (configure; start checks it is unchanged)")
    result.add_argument("--drone-root", type=Path, default=DEFAULT_DRONE_ROOT)
    result.add_argument("--viewer-root", type=Path, default=DEFAULT_VIEWER_ROOT)
    return result


def main(argv: list[str] | None = None) -> int:
    args = parser().parse_args(argv)
    drone_root = args.drone_root.expanduser().resolve()
    viewer_root = args.viewer_root.expanduser().resolve()
    if args.command == "configure":
        if args.recipe is None:
            raise FleetError("configure needs --recipe")
        return configure(drone_root, args.recipe)
    if args.command == "start":
        return start(drone_root, viewer_root, args.recipe)
    paths = workspace_paths()
    recipe = configured_recipe(paths)
    if args.command == "viewer-url":
        print(viewer_url(recipe["drone_count"]))
        return 0
    if args.command == "doctor":
        return base.doctor(experiment_path(paths), drone_root, viewer_root, workspace=paths,
                           launcher_writer=launcher_writer())
    if args.command == "status":
        return base.control(experiment_path(paths), drone_root, "status", workspace=paths)
    rc = base.control(experiment_path(paths), drone_root, "terminate", workspace=paths)
    if rc == 0:
        urban_lifecycle.verify_stopped(lifecycle_spec(paths, recipe["drone_count"]))
    return rc


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (FleetError, base.RecipeError, city.FleetMujocoError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
